spring.application.name=attendifyserver
spring.datasource.url=jdbc:postgresql://localhost:5432/attendify_db
spring.datasource.username=postgres
spring.datasource.password=rohan
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
server.port=8083